// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// H_stat_2s_1d_tr
double H_stat_2s_1d_tr(NumericVector a, NumericVector b);
RcppExport SEXP _HausdorffGoF_H_stat_2s_1d_tr(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(H_stat_2s_1d_tr(a, b));
    return rcpp_result_gen;
END_RCPP
}
// H_stat_2s_1d_p
double H_stat_2s_1d_p(NumericVector a, NumericVector b);
RcppExport SEXP _HausdorffGoF_H_stat_2s_1d_p(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(H_stat_2s_1d_p(a, b));
    return rcpp_result_gen;
END_RCPP
}
// H_stat_2s_2d
double H_stat_2s_2d(NumericMatrix x, NumericMatrix y, double tol);
RcppExport SEXP _HausdorffGoF_H_stat_2s_2d(SEXP xSEXP, SEXP ySEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(H_stat_2s_2d(x, y, tol));
    return rcpp_result_gen;
END_RCPP
}
// fastCDFOnSample_Rcpp
NumericVector fastCDFOnSample_Rcpp(NumericMatrix p_x_r);
RcppExport SEXP _HausdorffGoF_fastCDFOnSample_Rcpp(SEXP p_x_rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type p_x_r(p_x_rSEXP);
    rcpp_result_gen = Rcpp::wrap(fastCDFOnSample_Rcpp(p_x_r));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_HausdorffGoF_H_stat_2s_1d_tr", (DL_FUNC) &_HausdorffGoF_H_stat_2s_1d_tr, 2},
    {"_HausdorffGoF_H_stat_2s_1d_p", (DL_FUNC) &_HausdorffGoF_H_stat_2s_1d_p, 2},
    {"_HausdorffGoF_H_stat_2s_2d", (DL_FUNC) &_HausdorffGoF_H_stat_2s_2d, 3},
    {"_HausdorffGoF_fastCDFOnSample_Rcpp", (DL_FUNC) &_HausdorffGoF_fastCDFOnSample_Rcpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_HausdorffGoF(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
